name = "demo-project"

account_id = "15b0ccd4c68c56b4231b01eb799d53e8"
workers_dev = true  # Set this to false if deploying to a production environment
compatibility_flags = []

# Specify the path to your entry-point script
main = "./ancient-disk-7428/src/index.js"  # Adjust the path to your main Worker file

compatibility_date = "2025-03-14"